### ISSUE TITLE
Twitter Labs API

### ISSUE THREAD

**Issue by andypiper** [tomholford/twitter-labs-api#3]
Hello from Twitter Developer Relations!

First of all: Thank You, for building on our API, and for supporting our developer communities! You, and many projects like this one, are among the reasons why Twitter data is much-appreciated by developers. We historically haven't built libraries and SDKs - the communities, YOU, have done so - and I'm here to tell you how much we appreciate that, and that we know you're around!

As you are well aware by spending time working on the platform, we are currently building a brand new API platform that (over time) will replace the current one. I would love to connect with you on any plans to add further support for Twitter Developer Labs! We're looking to be much more focused on proper API versioning, and are basing our specification on OpenAPI.

Ruby has been one of the most valued and popular languages, since Twitter started (as a Ruby on Rails app, back in the day). Our twurl CLI is made in Ruby, and we know how popular Ruby is for interacting with the platform. Thank you, again!

**Comment by andypiper** [comment]
You might also be interested to know that today, we [announced the addition of annotations](https://twittercommunity.com/t/adding-annotations-to-tweets-and-recent-search-endpoints-in-labs/135193) to the Tweet objects in v2 of the API.

**Comment by tomholford** [comment]
@andypiper Thanks for the feedback. I am planning to implement all v2 endpoints in this gem, as they become released. thanks for the update on the annotations, eventually I hope to add support for that too. Please let me know if there is anything I can help you with!

**Comment by tonyv** [comment]
@tomholford Echoing what Andy has wrote here, I'm also on the Twitter Developer Relations team and also wanted to say thank you for building on top of our API. Do you have any v2 endpoints that you are prioritizing over others?

**Comment by tomholford** [comment]
@Tonyv Thanks for the checking in :) Next up is Metrics. 


As I mentioned to Andy, please lmk if there’s anything I can help with!

**Comment by tomholford** [comment]
@tonyv @andypiper Hey all, just an update that I have finished implementing all the v2 endpoints (Tweets and Users, Hidden Replies, and Recent Search). Feel free to check it out, and share this gem with others. And, feedback is welcome :) Thanks for an awesome new API :sparkles:

**Comment by andypiper** [comment]
Tom, this is excellent, thank you for working on this! We [recently announced that the new v2 API is about to launch](https://blog.twitter.com/developer/en_us/topics/tools/2020/introducing_new_twitter_api.html) (it would be available already if we could do it!), and as you've implemented Labs v2 I think you will find that this will work with just a few tweaks as soon as we are able to make the new API generally available!

Thank you!
